# Generated by Django 3.2.9 on 2021-11-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_auto_20211115_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
