# Generated by Django 3.2.9 on 2021-11-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_auto_20211118_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
