# Generated by Django 3.2.9 on 2021-11-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_remove_emprestimos_tempo_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Pessimo'), ('R', 'Ruim'), ('O', 'Ótimo'), ('B', 'Bom')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
