# Generated by Django 3.2.9 on 2021-11-21 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_auto_20211120_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('R', 'Ruim'), ('B', 'Bom'), ('P', 'Pessimo'), ('O', 'Ótimo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 22, 21, 18, 726794)),
        ),
    ]
